"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+xl5sie@crtmoji+_sa-ji6b3(_+z+knt6kw&dwr_$)(z91f#&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'application',
    'corsheaders',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOW_ALL_ORIGINS = True
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}
AUTH_USER_MODEL = 'application.User'

#to change in the future
SIGNATURE_THRESHOLD = 100 #default

# Since this is just an "allow-list" I decided that this is the best way to do it !
# This should be done with a table though i think
VALID_BIO_IDS = [
    "K1YL8VA2HG",
    "7DMPYAZAP2",
    "D05HPPQNJ4",
    "2WYIM3QCK9",
    "DHKFIYHMAZ",
    "LZK7P0X0LQ",
    "H5C98XCENC",
    "6X6I6TSUFG",
    "QTLCWUS8NB",
    "Y4FC3F9ZGS",
    "V30EPKZQI2",
    "O3WJFGR5WE",
    "SEIQTS1H16",
    "X16V7LFHR2",
    "TLFDFY7RDG",
    "PGPVG5RF42",
    "FPALKDEL5T",
    "2BIB99Z54V",
    "ABQYUQCQS2",
    "9JSXWO4LGH",
    "QJXQOUPTH9",
    "GOYWJVDA8A",
    "6EBQ28A62V",
    "30MY51J1CJ",
    "FH6260T08H",
    "JHDCXB62SA",
    "O0V55ENOT0",
    "F3ATSRR5DQ",
    "1K3JTWHA05",
    "FINNMWJY0G",
    "CET8NUAE09",
    "VQKBGSE3EA",
    "E7D6YUPQ6J",
    "BPX8O0YB5L",
    "AT66BX2FXM",
    "1PUQV970LA",
    "CCU1D7QXDT",
    "TTK74SYYAN",
    "4HTOAI9YKO",
    "PD6XPNB80J",
    "BZW5WWDMUY",
    "340B1EOCMG",
    "CG1I9SABLL",
    "49YFTUA96K",
    "V2JX0IC633",
    "C7IFP4VWIL",
    "RYU8VSS4N5",
    "S22A588D75",
    "88V3GKIVSF",
    "8OLYIE2FRC",
]