# Generated by Django 5.1.4 on 2025-01-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignatureThreshold',
        ),
    ]
